def get_card_image_string(card_rank = 0, card_suit = 0):

    image_path = 'images/Cards/8d.png'

    if (card_rank == 1)&(card_suit == 1): image_path = 'images/Cards/Ac.png'
    if (card_rank == 1)&(card_suit == 2): image_path = 'images/Cards/Ad.png'
    if (card_rank == 1)&(card_suit == 3): image_path = 'images/Cards/Ah.png'
    if (card_rank == 1)&(card_suit == 4): image_path = 'images/Cards/As.png'
    if (card_rank == 2)&(card_suit == 1): image_path = 'images/Cards/2c.png'
    if (card_rank == 2)&(card_suit == 2): image_path = 'images/Cards/2d.png'
    if (card_rank == 2)&(card_suit == 3): image_path = 'images/Cards/2h.png'
    if (card_rank == 2)&(card_suit == 4): image_path = 'images/Cards/2s.png'
    if (card_rank == 3)&(card_suit == 1): image_path = 'images/Cards/3c.png'
    if (card_rank == 3)&(card_suit == 2): image_path = 'images/Cards/3d.png'
    if (card_rank == 3)&(card_suit == 3): image_path = 'images/Cards/3h.png'
    if (card_rank == 3)&(card_suit == 4): image_path = 'images/Cards/3s.png'
    if (card_rank == 4)&(card_suit == 1): image_path = 'images/Cards/4c.png'
    if (card_rank == 4)&(card_suit == 2): image_path = 'images/Cards/4d.png'
    if (card_rank == 4)&(card_suit == 3): image_path = 'images/Cards/4h.png'
    if (card_rank == 4)&(card_suit == 4): image_path = 'images/Cards/4s.png'
    if (card_rank == 5)&(card_suit == 1): image_path = 'images/Cards/5c.png'
    if (card_rank == 5)&(card_suit == 2): image_path = 'images/Cards/5d.png'
    if (card_rank == 5)&(card_suit == 3): image_path = 'images/Cards/5h.png'
    if (card_rank == 5)&(card_suit == 4): image_path = 'images/Cards/5s.png'
    if (card_rank == 6)&(card_suit == 1): image_path = 'images/Cards/6c.png'
    if (card_rank == 6)&(card_suit == 2): image_path = 'images/Cards/6d.png'
    if (card_rank == 6)&(card_suit == 3): image_path = 'images/Cards/6h.png'
    if (card_rank == 6)&(card_suit == 4): image_path = 'images/Cards/6s.png'
    if (card_rank == 7)&(card_suit == 1): image_path = 'images/Cards/7c.png'
    if (card_rank == 7)&(card_suit == 2): image_path = 'images/Cards/7d.png'
    if (card_rank == 7)&(card_suit == 3): image_path = 'images/Cards/7h.png'
    if (card_rank == 7)&(card_suit == 4): image_path = 'images/Cards/7s.png'
    if (card_rank == 8)&(card_suit == 1): image_path = 'images/Cards/8c.png'
    if (card_rank == 8)&(card_suit == 2): image_path = 'images/Cards/8d.png'
    if (card_rank == 8)&(card_suit == 3): image_path = 'images/Cards/8h.png'
    if (card_rank == 8)&(card_suit == 4): image_path = 'images/Cards/8s.png'
    if (card_rank == 9)&(card_suit == 1): image_path = 'images/Cards/9c.png'
    if (card_rank == 9)&(card_suit == 2): image_path = 'images/Cards/9d.png'
    if (card_rank == 9)&(card_suit == 3): image_path = 'images/Cards/9h.png'
    if (card_rank == 9)&(card_suit == 4): image_path = 'images/Cards/9s.png'
    if (card_rank == 10)&(card_suit == 1): image_path = 'images/Cards/10c.png'
    if (card_rank == 10)&(card_suit == 2): image_path = 'images/Cards/10d.png'
    if (card_rank == 10)&(card_suit == 3): image_path = 'images/Cards/10h.png'
    if (card_rank == 10)&(card_suit == 4): image_path = 'images/Cards/10s.png'
    if (card_rank == 11)&(card_suit == 1): image_path = 'images/Cards/Jc.png'
    if (card_rank == 11)&(card_suit == 2): image_path = 'images/Cards/Jd.png'
    if (card_rank == 11)&(card_suit == 3): image_path = 'images/Cards/Jh.png'
    if (card_rank == 11)&(card_suit == 4): image_path = 'images/Cards/Js.png'
    if (card_rank == 12)&(card_suit == 1): image_path = 'images/Cards/Qc.png'
    if (card_rank == 12)&(card_suit == 2): image_path = 'images/Cards/Qd.png'
    if (card_rank == 12)&(card_suit == 3): image_path = 'images/Cards/Qh.png'
    if (card_rank == 12)&(card_suit == 4): image_path = 'images/Cards/Qs.png'
    if (card_rank == 13)&(card_suit == 1): image_path = 'images/Cards/Kc.png'
    if (card_rank == 13)&(card_suit == 2): image_path = 'images/Cards/Kd.png'
    if (card_rank == 13)&(card_suit == 3): image_path = 'images/Cards/Kh.png'
    if (card_rank == 13)&(card_suit == 4): image_path = 'images/Cards/Ks.png'

    return image_path
